// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConfigService lets the frontend browse and edit mod configs of a profile.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as configs$0 from "../configs/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ListConfigs(gameID: string, profileID: string): $CancellablePromise<configs$0.FileInfo[] | null> {
    return $Call.ByID(3441872064, gameID, profileID);
}

export function ReadConfig(gameID: string, profileID: string, path: string): $CancellablePromise<$models.ConfigContent> {
    return $Call.ByID(3676173335, gameID, profileID, path);
}

/**
 * SaveConfigChanges updates individual settings of a .cfg file, leaving the
 * rest of the file untouched.
 */
export function SaveConfigChanges(gameID: string, profileID: string, path: string, changes: configs$0.Change[] | null): $CancellablePromise<$models.ConfigContent> {
    return $Call.ByID(1482945187, gameID, profileID, path, changes);
}

/**
 * SaveConfigText replaces a config file's contents.
 */
export function SaveConfigText(gameID: string, profileID: string, path: string, text: string): $CancellablePromise<$models.ConfigContent> {
    return $Call.ByID(2151844933, gameID, profileID, path, text);
}
