// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * IconService provides game icons as data URLs, so the webview can show local
 * Steam cache files.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * GetSteamIcon returns the icon of a Steam app as a data URL, or "" if none is cached.
 */
export function GetSteamIcon(appID: string): $CancellablePromise<string> {
    return $Call.ByID(586910799, appID);
}
