// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as configs$0 from "../configs/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as github$0 from "../github/models.js";

export interface AppInfo {
    "name": string;
    "version": string;
    "os": string;
    "arch": string;

    /**
     * SteamDeck reports whether Hermit runs on a Steam Deck, which decides
     * the interface layout when the UI mode is set to auto.
     */
    "steamDeck": boolean;
}

export interface ConfigContent {
    "path": string;
    "text": string;

    /**
     * Document is the parsed structure of .cfg files, nil for other files.
     */
    "document": configs$0.Document | null;
}

export interface GitHubRepo {
    "owner": string;
    "repo": string;
    "releases": github$0.Release[] | null;
}

export interface LaunchInfo {
    /**
     * Supported is false when the manager cannot launch the game with mods;
     * Reason explains why.
     */
    "supported": boolean;
    "reason": string;

    /**
     * LaunchOptions is the value to put into the game's Steam Launch Options.
     */
    "launchOptions": string;

    /**
     * Configured reports whether Steam's saved config has these launch options.
     * Steam writes its config lazily, so false may just mean "not saved yet".
     */
    "configured": boolean;
    "running": boolean;

    /**
     * RunningProfile is the profile of the running session, if any.
     */
    "runningProfile": string;
}
