// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Dependency is a [BepInDependency] on another plugin GUID.
 */
export interface Dependency {
    "guid": string;
    "soft": boolean;

    /**
     * MinVersion is set by the (guid, version range) constructor.
     */
    "minVersion": string;
}

/**
 * Plugin is a class marked with [BepInPlugin].
 */
export interface Plugin {
    "guid": string;
    "name": string;
    "version": string;

    /**
     * Class is the full name of the plugin class.
     */
    "class": string;
    "dependencies": Dependency[] | null;
    "incompatibilities": string[] | null;

    /**
     * Processes limits the plugin to these game executables, if any.
     */
    "processes": string[] | null;
}
