// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Change sets the value of one entry; Line comes from ParseCfg and Section
 * and Key guard against the file having changed in between.
 */
export interface Change {
    "section": string;
    "key": string;
    "line": number;
    "value": string;
}

export interface Document {
    /**
     * Header holds the description lines before the first section.
     */
    "header": string[] | null;
    "sections": Section[] | null;
}

export interface Entry {
    "key": string;
    "value": string;

    /**
     * Line is the 0-based line of "key = value", used to save changes.
     */
    "line": number;
    "description": string;

    /**
     * Type is BepInEx's setting type, e.g. Boolean, Int32, Single, String, or an enum name.
     */
    "type": string;
    "default": string;

    /**
     * HasDefault distinguishes an empty default from a missing one.
     */
    "hasDefault": boolean;

    /**
     * AcceptableValues lists enum values; Multiple means flags that combine with ", ".
     */
    "acceptableValues": string[] | null;
    "multiple": boolean;

    /**
     * Min and Max bound numeric settings when HasRange is set.
     */
    "hasRange": boolean;
    "min": number;
    "max": number;
}

export interface FileInfo {
    /**
     * Path is slash-separated, relative to the profile.
     */
    "path": string;
    "size": number;
    "modTime": string;

    /**
     * Plugin is the plugin name from the header BepInEx writes, if any.
     */
    "plugin": string;
}

export interface Section {
    "name": string;
    "entries": Entry[] | null;
}
