// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Settings {
    /**
     * SetupCompleted is set once the first-run setup is finished or skipped.
     */
    "setupCompleted": boolean;

    /**
     * AllowNSFW shows packages marked NSFW when browsing mods.
     */
    "allowNsfw": boolean;
}
