// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../library/models.js";

export enum Action {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ActionInstall = "install",
    ActionUpdate = "update",
    ActionReinstall = "reinstall",
};

export interface Conflict {
    /**
     * Package is the planned package, "<author>-<name>-<version>".
     */
    "package": string;

    /**
     * ModID is the conflicting mod: installed, or another planned package.
     */
    "modId": string;
    "modName": string;
    "installed": boolean;
    "reason": ConflictReason;

    /**
     * Blocking conflicts cannot be solved by replacing: the other side is
     * itself part of, or required by, the packages being installed.
     */
    "blocking": boolean;

    /**
     * Files lists some of the shared files.
     */
    "files": string[] | null;
}

export enum ConflictReason {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    /**
     * ConflictFiles means both packages install the same files.
     */
    ConflictFiles = "files",

    /**
     * ConflictLoader means both packages are BepInEx loader packs; only one can be installed.
     */
    ConflictLoader = "loader",
};

export interface InstallPlan {
    "packages": PlannedPackage[] | null;
    "conflicts": Conflict[] | null;
}

/**
 * Options control how a package is installed.
 */
export interface Options {
    /**
     * ReplaceConflicts uninstalls installed mods that conflict with the
     * packages being installed.
     */
    "replaceConflicts": boolean;

    /**
     * Modpack installs exact dependency versions, so everyone installing the
     * same modpack gets the same set of mods.
     */
    "modpack": boolean;
}

export interface PlannedPackage {
    /**
     * Package is "<author>-<name>-<version>".
     */
    "package": string;
    "action": Action;
}

export interface Progress {
    "gameId": string;
    "profileId": string;

    /**
     * Target is the package the user asked to install ("<author>-<name>").
     */
    "target": string;

    /**
     * Package is the package currently being processed, a dependency or the target.
     */
    "package": string;
    "stage": Stage;

    /**
     * Done and Total are bytes of the current download.
     */
    "done": number;
    "total": number;

    /**
     * Step and Steps count packages: finished and known downloads while
     * downloading, the current and total package while installing.
     */
    "step": number;
    "steps": number;
}

export enum Stage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StageDownload = "download",
    StageInstall = "install",
};

/**
 * Update is an installed mod with a newer version available.
 */
export interface Update {
    "modId": string;
    "current": string;
    "latest": string;
}

export interface UpdateResult {
    "profile": library$0.Profile;
    "updated": string[] | null;

    /**
     * Failed maps mod ids to the reason they could not be updated.
     */
    "failed": { [_ in string]?: string } | null;
}
