// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Category {
    "id": string;
    "name": string;
    "slug": string;
}

/**
 * Community is a Thunderstore community (one per game).
 */
export interface Community {
    "id": string;
    "name": string;
}

export interface Dependency {
    "namespace": string;
    "name": string;
    "version_number": string;
    "description": string;
    "icon_url": string;
    "is_unavailable": boolean;
}

export interface Filters {
    "categories": Category[] | null;
    "sections": Section[] | null;
}

export interface ListOptions {
    "query": string;
    "ordering": Ordering;

    /**
     * Section is a section UUID from Filters; empty means all packages.
     */
    "section": string;
    "page": number;
}

export enum Ordering {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    OrderLastUpdated = "last-updated",
    OrderNewest = "newest",
    OrderMostDownloaded = "most-downloaded",
    OrderTopRated = "top-rated",
};

export interface PackageDetail {
    "namespace": string;
    "name": string;
    "description": string;
    "icon_url": string;
    "website_url": string;
    "download_count": number;
    "rating_count": number;
    "size": number;
    "latest_version_number": string;
    "version_count": number;
    "version_created": string;
    "download_url": string;
    "is_deprecated": boolean;
    "categories": Category[] | null;
    "dependencies": Dependency[] | null;
    "dependant_count": number;

    /**
     * PageURL is the package page on the Thunderstore website.
     */
    "page_url": string;
}

export interface PackageList {
    "count": number;
    "page": number;
    "has_more": boolean;
    "packages": PackageSummary[] | null;
}

export interface PackageSummary {
    "namespace": string;
    "name": string;
    "description": string;
    "icon_url": string;
    "download_count": number;
    "rating_count": number;
    "size": number;
    "last_updated": string;
    "is_pinned": boolean;
    "is_deprecated": boolean;
    "categories": Category[] | null;
}

export interface Section {
    "uuid": string;
    "name": string;
    "slug": string;
    "priority": number;
}
