// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowseView is how the mod browser lists packages. Auto follows the layout:
 * cards on the deck, a list on the desktop.
 */
export enum BrowseView {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    BrowseViewAuto = "auto",
    BrowseViewCards = "cards",
    BrowseViewList = "list",
};

export interface Settings {
    /**
     * SetupCompleted is set once the first-run setup is finished or skipped.
     */
    "setupCompleted": boolean;

    /**
     * AllowNSFW shows packages marked NSFW when browsing mods.
     */
    "allowNsfw": boolean;

    /**
     * UIMode is the interface layout; empty means auto.
     */
    "uiMode": UIMode;

    /**
     * BrowseView is the mod browser layout; empty means auto.
     */
    "browseView": BrowseView;
}

/**
 * UIMode selects the interface layout. Auto follows the hardware: the Steam
 * Deck gets the deck layout, everything else the desktop one.
 */
export enum UIMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    UIModeAuto = "auto",
    UIModeDesktop = "desktop",
    UIModeDeck = "deck",
};
