// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CompleteSetup(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3224027075);
}

export function Get(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(4255639083);
}

/**
 * Update replaces user-editable preferences; SetupCompleted is kept as stored.
 */
export function Update(st: $models.Settings): $CancellablePromise<$models.Settings> {
    return $Call.ByID(971130280, st);
}
