// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../library/models.js";

export interface ExportMod {
    /**
     * Name is "<author>-<name>".
     */
    "name": string;
    "version": Version;
    "enabled": boolean;
}

export interface FailedMod {
    "package": string;
    "error": string;
}

export interface ImportProgress {
    "gameId": string;
    "profileId": string;

    /**
     * Package is the mod being installed, "<author>-<name>-<version>".
     */
    "package": string;
    "done": number;
    "total": number;
}

export interface ImportResult {
    "profile": library$0.Profile;

    /**
     * Failed lists mods that could not be installed, e.g. removed from Thunderstore.
     */
    "failed": FailedMod[] | null;
}

export interface Preview {
    /**
     * Archive is the local .r2z file to pass to Import.
     */
    "archive": string;
    "profileName": string;
    "mods": ExportMod[] | null;
}

/**
 * Source is a profile to import: an .r2z file or a profile code.
 */
export interface Source {
    "file": string;
    "code": string;
}

export interface Version {
    "major": number;
    "minor": number;
    "patch": number;
}
