// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Asset {
    "name": string;
    "size": number;
    "browser_download_url": string;
}

export interface Release {
    "tag_name": string;
    "name": string;
    "prerelease": boolean;
    "draft": boolean;
    "published_at": string;
    "assets": Asset[] | null;
}
