// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Progress {
    "gameId": string;
    "profileId": string;

    /**
     * Target is the package the user asked to install ("<author>-<name>").
     */
    "target": string;

    /**
     * Package is the package currently being processed, a dependency or the target.
     */
    "package": string;
    "stage": Stage;
    "done": number;
    "total": number;
}

export enum Stage {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    StageDownload = "download",
    StageInstall = "install",
};
