// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowseService lets the frontend browse Thunderstore packages for a game.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as thunderstore$0 from "../thunderstore/models.js";

/**
 * GetCommunity returns the Thunderstore community of a game, or ErrNoCommunity.
 */
export function GetCommunity(gameID: string): $CancellablePromise<thunderstore$0.Community> {
    return $Call.ByID(2491043851, gameID);
}

export function GetFilters(community: string): $CancellablePromise<thunderstore$0.Filters> {
    return $Call.ByID(1825591857, community);
}

export function GetPackage(community: string, $namespace: string, name: string): $CancellablePromise<thunderstore$0.PackageDetail> {
    return $Call.ByID(2731032766, community, $namespace, name);
}

export function GetReadme($namespace: string, name: string, version: string): $CancellablePromise<string> {
    return $Call.ByID(756038540, $namespace, name, version);
}

export function ListPackages(community: string, opts: thunderstore$0.ListOptions): $CancellablePromise<thunderstore$0.PackageList> {
    return $Call.ByID(2514346247, community, opts);
}
