// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as library$0 from "../library/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modinstall$0 from "../modinstall/models.js";

/**
 * CheckUpdates lists installed Thunderstore mods with a newer version.
 */
export function CheckUpdates(gameID: string, profileID: string): $CancellablePromise<modinstall$0.Update[] | null> {
    return $Call.ByID(1740444231, gameID, profileID);
}

/**
 * InstallPackage installs a Thunderstore package version with its dependencies
 * into a profile, emitting InstallProgressEvent along the way. Conflicting
 * installed mods are uninstalled only if opts.ReplaceConflicts is set.
 */
export function InstallPackage(gameID: string, profileID: string, $namespace: string, name: string, version: string, opts: modinstall$0.Options): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(3825584552, gameID, profileID, $namespace, name, version, opts);
}

/**
 * OpenProfile returns a profile with mod states brought up to date.
 */
export function OpenProfile(gameID: string, profileID: string): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(2168871490, gameID, profileID);
}

/**
 * PlanInstall downloads a package with its dependencies and reports what
 * installing it would change, including conflicts with installed mods.
 */
export function PlanInstall(gameID: string, profileID: string, $namespace: string, name: string, version: string, opts: modinstall$0.Options): $CancellablePromise<modinstall$0.InstallPlan> {
    return $Call.ByID(3551015545, gameID, profileID, $namespace, name, version, opts);
}

/**
 * SetModEnabled enables or disables a mod; dependants follow automatically.
 */
export function SetModEnabled(gameID: string, profileID: string, modID: string, enabled: boolean): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(3019243778, gameID, profileID, modID, enabled);
}

export function UninstallMod(gameID: string, profileID: string, modID: string): $CancellablePromise<library$0.Profile> {
    return $Call.ByID(1415825551, gameID, profileID, modID);
}

/**
 * UpdateAll updates every outdated mod, emitting InstallProgressEvent.
 */
export function UpdateAll(gameID: string, profileID: string): $CancellablePromise<modinstall$0.UpdateResult> {
    return $Call.ByID(554059943, gameID, profileID);
}
