// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function GetLaunchInfo(gameID: string): $CancellablePromise<$models.LaunchInfo> {
    return $Call.ByID(2016763558, gameID);
}

/**
 * Play makes the profile active and starts the game through Steam. Mods load
 * only if the game's launch options run it through the wrapper.
 */
export function Play(gameID: string, profileID: string): $CancellablePromise<void> {
    return $Call.ByID(100397041, gameID, profileID);
}
