// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ShareService exports and imports profiles in r2modman's format.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as profileshare$0 from "../profileshare/models.js";

/**
 * ExportCode uploads the profile to Thunderstore and returns a code anyone can import.
 */
export function ExportCode(gameID: string, profileID: string): $CancellablePromise<string> {
    return $Call.ByID(101770858, gameID, profileID);
}

export function ExportFile(gameID: string, profileID: string, dest: string): $CancellablePromise<void> {
    return $Call.ByID(3441545005, gameID, profileID, dest);
}

/**
 * Import creates a profile from a previewed archive, emitting
 * ImportProgressEvent and InstallProgressEvent along the way.
 */
export function Import(gameID: string, archive: string, name: string): $CancellablePromise<profileshare$0.ImportResult> {
    return $Call.ByID(1449284596, gameID, archive, name);
}

export function PreviewImport(src: profileshare$0.Source): $CancellablePromise<profileshare$0.Preview> {
    return $Call.ByID(587226262, src);
}
